# Generated by Django 5.2.5 on 2025-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
